Migrating to new apis
suzil/radis-app pull request #597
Opened 2022-06-28 18:51 UTC by arunavabasu-03

Fixes #595

2022-06-29 12:25 UTC, suzil commented on frontend/.gitignore
> +!radis.d.ts
We don't need this. We exclude the ignoring of this file in the parent gitignore. In addition, this isn't the path it's on (it's under `src/`).

2022-06-29 12:30 UTC, suzil reviewed
To make this easier to review, would you rebase your commits and adjust it to something like the following:
- First commit: "Rename website/ to frontend/" (and only have changes related to that there)
- Second commit: "Migrate to MUI module imports"

I also think we don't need to add headers to the imports. It should be pretty self-explanatory that an import is a MUI module import that we don't need to label it with a comment.

2022-06-30 16:44 UTC, suzil requested changes
Adjust `package.json` yarn install script to do `cd frontend/` instead of `cd website/` as right now that doesn't work.

2022-06-30 21:11 UTC, suzil commented on package.json
>      "build": "tsc && cd website && yarn build",
also here should be "frontend"

2022-07-01 14:08 UTC, arunavabasu-03 commented
@suzil now all things all ok :)
Hitran             |  Geisa
:-------------------------:|:-------------------------:
<img width="1411" alt="Screenshot 2022-07-01 at 7 30 39 PM" src="https://user-images.githubusercontent.com/73842340/176909723-308cae44-4f1a-494a-8e0d-b263a1ebaf7d.png">  |  <img width="1416" alt="Screenshot 2022-07-01 at 7 30 23 PM" src="https://user-images.githubusercontent.com/73842340/176909747-1c72b50e-c119-4552-97e6-f8c8e42bdbd3.png">

2022-07-01 14:09 UTC, arunavabasu-03 commented on frontend/src/components/fields/MoleculeSelector/index.tsx
> +        return <li {...props}>{addSubscriptsToMolecule(molecule)}</li>;
basically, we render this in this way.

2022-07-05 13:13 UTC, suzil commented on frontend/src/components/fields/MoleculeSelector/index.tsx
> +      }}
We don't want the `console.log` on prod here.

```suggestion
      renderOption={(props, molecule) => <li {...props}>{addSubscriptsToMolecule(molecule)}</li>}
```

2022-07-05 14:41 UTC, arunavabasu-03 commented
@suzil , fixed :)

<img width="1248" alt="Screenshot 2022-07-05 at 8 09 37 PM" src="https://user-images.githubusercontent.com/73842340/177353884-825cdd7a-8ea9-4a03-86a7-517578a31fc0.png">

2022-07-05 18:19 UTC, suzil commented on .gitignore
>  # /Users/arunavabasu/Work/Web/GSOC/radis-app/website/radis.d.ts
```suggestion
```
Would be nice to just remove entirely instead of leaving it commented-out.

2022-07-05 18:21 UTC, suzil approved these changes

2022-07-05 18:21 UTC, merged