Adding Simulate slit
suzil/radis-app pull request #610
Opened 2022-07-19 15:56 UTC by arunavabasu-03

Add slit as a field so that users may apply it as they want !!

2022-07-19 18:56 UTC, suzil commented on server/main.py
> +            pass
I think we can simplify it a bit to just check if the value is None or not.
```suggestion
        if simulate_slit is not None:
            spectrum.apply_slit(payload.simulate_slit, "nm")
```

2022-07-19 19:02 UTC, suzil commented on server/main.py
> +            pass
I would remove this "else pass" to keep the code more minimal so it's easier to read

2022-07-19 19:09 UTC, suzil commented
I think the UI might be a bit confusing for users when they don't want to simulate a slit as right now they would have to leave the textfield with no value.

<img width="638" alt="Screen Shot 2022-07-19 at 3 08 25 PM" src="https://user-images.githubusercontent.com/13723264/179829600-692906aa-345a-4b6a-a734-ac07ba4419c1.png">

I wonder if a better UI setup could be to use a "simulate slit" slider to ask the user whether or not they want to simulate a slit, and if the user activates the slider, then a new text field appears that prompts them for how big the slit should be.
 
Thoughts here @erwanp?

2022-07-19 19:22 UTC, arunavabasu-03 commented
@suzil, slider, or switch ??

2022-07-19 19:39 UTC, suzil commented
Sorry I meant switch!

2022-07-20 16:59 UTC, erwanp commented
Btw i'm noticing a small glitch 
![image](https://user-images.githubusercontent.com/16088743/180040263-d0f1453f-5c0e-4413-88be-bcdacaa29c77.png)

2022-07-23 17:08 UTC, suzil commented
@arunavabasu-03 In the future, would you write your commits according to this style guide? https://cbea.ms/git-commit/

Right now I'm trying to track when our frontend stopped running locally and some of the commit messages make it more difficult for me to go through the history and know what's going on because the commit messages are too vague.

2022-07-24 13:43 UTC, suzil commented on frontend/src/components/fields/Mode.tsx
> +            <MenuItem value={"radiance_noslit "}>Radiance </MenuItem>
```suggestion
            <MenuItem value={"radiance_noslit"}>Radiance </MenuItem>
```

2022-07-24 13:45 UTC, suzil commented on frontend/src/components/CalcSpectrum.tsx
> +  const [useSlitSwitch, setuseSlitSwitch] = useState(false);
```suggestion
  const [useSlitSwitch, setUseSlitSwitch] = useState(false);
```

2022-07-24 17:18 UTC, arunavabasu-03 commented
@suzil  done

2022-07-24 22:23 UTC, suzil commented
I want to run the backend locally to test the changes made to both the frontend and the backend, but I'm having this bug with GEISA: https://github.com/radis/radis/issues/497

2022-07-27 13:16 UTC, suzil commented on frontend/src/components/types.ts
> +  useSimulateSlit: boolean;
For consistency with the other form values, I would switch this to snake_case.

2022-07-27 13:17 UTC, suzil commented on server/main.py
> +        if simulate_slit is not None:
Since we're already passing the value, we could do something like `if useSimulateSlit:`

2022-07-27 13:17 UTC, suzil commented
I would have the simulate slit amount appear below the switch so that the user filling out the form works in a single direction (down).

https://user-images.githubusercontent.com/13723264/181255968-41556b04-6c94-45d7-a2b1-08a607a03224.mov

2022-07-27 13:17 UTC, suzil requested changes
A couple of small comments but it looks great!

2022-07-27 17:02 UTC, erwanp commented
Hello, couple suggestinos : 

- Use "Apply Instrumental Slit Function" for Switch
- As label of input box use "Slit Size"

Can you also make the Slit size input box appear on the right of the Switch ? , or, if it doesn't work well, below the switch ?

2022-07-28 16:09 UTC, arunavabasu-03 commented
@erwanp, check !!

<img width="507" alt="Screenshot 2022-07-28 at 9 37 54 PM" src="https://user-images.githubusercontent.com/73842340/181586023-0ae46dea-f59a-4053-b7cd-60144672876e.png">

2022-07-29 18:48 UTC, suzil approved these changes
Great work!

2022-07-29 18:48 UTC, merged